version = 1

[[annotations]]
path = "Cargo.lock"
SPDX-FileCopyrightText = "2022 Harish Rajagopal <harish.rajagopals@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "testdata/scraping/**.html"
SPDX-FileCopyrightText = "2023 Internet Archive <https://archive.org/>"
SPDX-License-Identifier = "LicenseRef-Archive.org"
