name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      id: toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: beta
          override: true
          components: rustfmt, clippy
    - name: Restore build cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ steps.toolchain.outputs.rustc_hash }}-
    - name: Build
      run: cargo build --tests --verbose
    - name: pre-commit
      uses: pre-commit/action@v3.0.0
    - uses: pre-commit-ci/lite-action@v1.0.0
      if: always()
    - name: Run tests
      run: cargo test --verbose
